// Item
// Item Remove
export const ITEM_REMOVE = 'ITEM_REMOVE';
export const ITEM_REMOVE_SUCCESS = 'ITEM_REMOVE_SUCCESS';
export const ITEM_REMOVE_FAILURE = 'ITEM_REMOVE_FAILURE';
// Item Load
export const ITEM_LOAD = 'ITEM_LOAD';
export const ITEM_LOAD_SUCCESS = 'ITEM_LOAD_SUCCESS';
export const ITEM_LOAD_FAILURE = 'ITEM_LOAD_FAILURE';


export const ITEM_SELECTED = 'ITEM_SELECTED';

// Items
export const ITEMS_LOAD = 'ITEMS_LOAD';
export const ITEMS_LOAD_SUCCESS = 'ITEMS_LOAD_SUCCESS';
export const ITEMS_LOAD_FAILURE = 'ITEMS_LOAD_FAILURE';
export const ITEMS_FILTER_CHANGE = 'ITEMS_FILTER_CHANGE';
// Categories
export const CATEGORIES_LOAD = 'CATEGORIES_LOAD';
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS';
export const CATEGORIES_LOAD_FAILURE = 'CATEGORIES_LOAD_FAILURE';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';

// PAGE PRELOADER
export const PAGE_PRELOADER_STARTED = 'PAGE_PRELOADER_STARTED';
