// Item
export const ITEM_REMOVE = 'ITEM_REMOVE';
export const ITEM_LOAD = 'ITEM_LOAD';
export const ITEM_LOAD_SUCCESS = 'ITEM_LOAD_SUCCESS';
export const ITEM_LOAD_FAILURE = 'ITEM_LOAD_FAILURE';
// Items
export const ITEMS_INIT = 'ITEMS_INIT';
export const ITEMS_INIT_SUCCESS = 'ITEMS_INIT_SUCCESS';
export const ITEMS_INIT_FAILURE = 'ITEMS_INIT_FAILURE';
export const ITEMS_FILTER_INIT = 'ITEMS_FILTER_INIT';
// Categories
export const CATEGORIES_LOAD = 'CATEGORIES_LOAD';
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS';
export const CATEGORIES_LOAD_FAILURE = 'CATEGORIES_LOAD_FAILURE';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
